language: c

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/build/lairdm/apache-faidx/htslib

env:
  - COVERALLS=true
  - COVERALLS=false

addons:
  apt:
    packages:
      - apache2-prefork-dev
      - apache2-mpm-prefork
      - curl
      - ruby-dev
      - lcov

before_install:
  - if [ -d "htslib1" ]; then (cd htslib && git pull); else git clone --branch develop --depth 1 https://github.com/lairdm/htslib.git; fi
  - cd htslib
  - pwd
  - make
  - sudo make install
  - export HTSLIB_DIR=$(pwd -P)
  - cd ..
  - sudo ldconfig
  - which gem
  - gem install coveralls-lcov

install:  
  - export APACHE_FAIDX_DIR=$(pwd -P)
  - sed -i -e 's@APACHE_FAIDX_DIR@'$APACHE_FAIDX_DIR'@g' t/faidx.conf
  - sed -i -e 's@APACHE_FAIDX_DIR@'$APACHE_FAIDX_DIR'@g' t/faidx_coveralls.load
  - if [[ "$COVERALLS" == "true" ]]; then sudo ln -s $(pwd -P)/t/faidx_coveralls.load /etc/apache2/mods-enabled/faidx.load; else sudo ln -s $(pwd -P)/t/faidx.load /etc/apache2/mods-enabled/; fi
  - sudo ln -s $(pwd -P)/t/faidx.conf /etc/apache2/mods-enabled/
  - ls -l /etc/apache2/mods-enabled/
  - if [[ "$COVERALLS" == "true" ]]; then lcov --directory . --zerocounters; fi
  - if [[ "$COVERALLS" == "true" ]]; then make coveralls; else make debug; fi
  - if [[ "$COVERALLS" == "false" ]]; then sudo make install; fi
  - sudo apache2ctl restart

script:
  - curl "http://localhost/faidx?set=human&location=1%3A1000-2000"
  - curl "http://localhost/faidx?set=human&location=Y%3A1000-2000"
  - curl "http://localhost/faidx/sets"
  - curl "http://localhost/faidx/locations/cat/"
  - curl "http://localhost/faidx/locations/human/"
  - /usr/sbin/apachectl -V

after_success:
  - if [[ "$COVERALLS" == "true" ]]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then lcov --list coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then coveralls-lcov --repo-token riAPmHw8OAaaaitWA26yBEIpGYLGyXQ6w coverage.info; fi
  - sudo cat /var/log/apache2/error.log

after_failure:
  - sudo cat /var/log/apache2/error.log

notifications:
  email:
    on_success: change
    on_failure: change
