language: c

cache:
  directories:
    - $HOME/build/lairdm/apache-faidx/htslib

addons:
  apt:
    packages:
      - apache2-prefork-dev
      - apache2-mpm-prefork

before_install:
  - if [ -d htslib ]; then (cd repo && git pull); else git clone --branch develop --depth 1 https://github.com/lairdm/htslib.git; fi
  - cd htslib
  - make
  - sudo make install
  - export HTSLIB_DIR=$(pwd -P)
  - cd ..

install:  
  - make
  - sudo make install
  - export APACHE_FAIDX_DIR=$(pwd -P)
  - ln -s $(pwd -P)/t/faidx.load /etc/apache2/mods-enabled/
  - ln -s $(pwd -P)/t/faidx.conf /etc/apache2/mods-enabled/
  - sudo apache2ctl restart

script:
  - ps aux
