language: c

cache:
  directories:
    - $HOME/build/lairdm/apache-faidx/htslib

addons:
  apt:
    packages:
      - apache2-prefork-dev
      - apache2-mpm-prefork
      - curl

before_install:
  - if [ -d htslib ]; then (cd htslib && git pull); else git clone --branch develop --depth 1 https://github.com/lairdm/htslib.git; fi
  - cd htslib
  - make
  - sudo make install
  - export HTSLIB_DIR=$(pwd -P)
  - cd ..
  - sudo ldconfig

install:  
  - make debug
  - sudo make install
  - export APACHE_FAIDX_DIR=$(pwd -P)
  - sed -i -e 's@APACHE_FAIDX_DIR@'$APACHE_FAIDX_DIR'@g' t/faidx.conf
  - sudo ln -s $(pwd -P)/t/faidx.load /etc/apache2/mods-enabled/
  - sudo ln -s $(pwd -P)/t/faidx.conf /etc/apache2/mods-enabled/
  - sudo apache2ctl restart

script:
  - curl "http://localhost/faidx?set=human&location=1%3A1000-2000"
  - curl "http://localhost/faidx/sets"
  - curl "http://localhost/faidx/locations/cat/"
  - curl "http://localhost/faidx/locations/human/"
  - /usr/sbin/apachectl -V

after_success:
  - sudo cat /var/log/apache2/error.log

after_failure:
  - sudo cat /var/log/apache2/error.log
