language: c

#cache:
#  directories:
#    - $HOME/build/lairdm/apache-faidx/htslib

env:
  - COVERALLS=true
  - COVERALLS=false

addons:
  apt:
    packages:
      - apache2-prefork-dev
      - apache2-mpm-prefork
      - curl
      - ruby-dev
      - lcov

before_install:
  - if [ -d htslib ]; then (cd htslib && git pull); else git clone --branch develop --depth 1 https://github.com/lairdm/htslib.git; fi
  - cd htslib
  - pwd
  - make
  - sudo make install
  - export HTSLIB_DIR=$(pwd -P)
  - cd ..
  - sudo ldconfig
  - sudo gem install coveralls-lcov

before_script:
  - if [[ "$COVERALLS" == "true" ]]; then lcov --directory . --zerocounters; fi

install:  
  - export APACHE_FAIDX_DIR=$(pwd -P)
  - sed -i -e 's@APACHE_FAIDX_DIR@'$APACHE_FAIDX_DIR'@g' t/faidx.conf
  - sed -i -e 's@APACHE_FAIDX_DIR@'$APACHE_FAIDX_DIR'@g' t/faidx_coveralls.load
  - sudo ln -s $(pwd -P)/t/faidx.load /etc/apache2/mods-enabled/
  - sudo ln -s $(pwd -P)/t/faidx.conf /etc/apache2/mods-enabled/
  - if [[ "$COVERALLS" == "true" ]]; then sudo ln -f -s $(pwd -P)/t/faidx_coveralls.load /etc/apache2/mods-enabled/faidx.load; fi
  - if [[ "$COVERALLS" == "true" ]]; then make coveralls; else make debug; fi
  - sudo make install
  - sudo apache2ctl restart

script:
  - curl "http://localhost/faidx?set=human&location=1%3A1000-2000"
  - curl "http://localhost/faidx/sets"
  - curl "http://localhost/faidx/locations/cat/"
  - curl "http://localhost/faidx/locations/human/"
  - /usr/sbin/apachectl -V

after_success:
  - if [[ "$COVERALLS" == "true" ]]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then lcov --remove coverage.info 't/*' --output-file coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then lcov --list coverage.info; fi
  - if [[ "$COVERALLS" == "true" ]]; then coveralls-lcov --repo-token riAPmHw8OAaaaitWA26yBEIpGYLGyXQ6w coverage.info; fi
  - sudo cat /var/log/apache2/error.log

after_failure:
  - sudo cat /var/log/apache2/error.log
